apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvclaim
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi # can be less, divided between claims
