apiVersion: v1
kind: Service
metadata:
  name:  auth-service
spec:
  selector:
    app:  auth
  type:  ClusterIP # ClusterIP default (only inside), NodePort (external, but changes the IP when have replicas)
  ports:
  - protocol:  TCP
    port:  80
    targetPort:  80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: oreynaldocl/kub-demo-auth:latest
          name: auth
